Candidate results headers
traitify/traitify-widgets pull request #189
Opened 2020-03-02 22:35 UTC by Jbur43

2020-03-12 20:20 UTC, tomprats commented
@Jbur43 This change might not doable as-is. If our customers using the widgets have their own headings, this would add an extra one. I'd either check with @efleming that it'd be fine, or we could just add an option to add the heading conditionally. Like `allowHeadings` with a false default

2020-09-23 15:46 UTC, tomprats requested changes

2020-09-23 15:46 UTC, tomprats commented on src/components/results/candidate-results/personality-dimension-details/index.js
> +class PersonalityDimensionDetails extends Component {
I think this component was folded over into components/results/personality/dimension/details

2020-09-23 15:46 UTC, tomprats commented on test/components/results/__snapshots__/candidate-results.test.js.snap
> +<<<<<<< HEAD
Some merge errors

2020-09-23 15:46 UTC, tomprats commented on test/components/results/__snapshots__/candidate-results.test.js.snap
> +<<<<<<< HEAD
Some merge errors

2020-09-23 15:46 UTC, tomprats commented on test/components/results/__snapshots__/candidate-results.test.js.snap
> +<<<<<<< HEAD
Some merge errors

2020-09-23 15:46 UTC, tomprats commented on test/components/results/personality/dimension/__snapshots__/details.test.js.snap
> -exports[`PersonalityDimensionDetails renders component 1`] = `
I think this should still exist

2020-09-30 16:25 UTC, Jbur43 commented
Sorry meant for that to be a WIP commit

2020-10-05 18:13 UTC, tomprats reviewed
I think it looks great but two things:

1. Do we need to have it for more of the views? Looks like this is just the candidate view
2. Could we also have a disableHeaders function. Just good to have both options, even if it does disable by default

2020-10-23 18:38 UTC, Jbur43 commented
Spoke with Eric and ended up adding them for Type Based Results. Also added the disableHeaders function

2020-10-26 15:58 UTC, tomprats reviewed
I think it's just missing two translation values but everything else looks great!

2020-10-26 15:58 UTC, tomprats commented on src/lib/i18n-data/ja_jp.json
> +  "personality_blend": "",
I think we want a value here

2020-10-26 15:58 UTC, tomprats commented on src/lib/i18n-data/ht_us.json
> +  "personality_blend": "",
And here

2020-12-03 23:02 UTC, tomprats approved these changes

2020-12-03 23:48 UTC, merged